name: .NET backend

on:
  pull_request:
    branches: [ "master", "dev" ]
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/dotnet-build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore Trusov.NET.sln
      - name: Build
        run: dotnet build --no-restore Trusov.NET.sln
  
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Test
        run: dotnet test --no-build --verbosity normal Trusov.NET.sln
      - name: Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history 
      - name: Post allure test run link
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            Link to allure test run:  
            https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ github.run_number }}